env:
DOCKER_USERNAME: DOCKER_USERNAME
DOCKER_PASSWORD: DOCKER_PASSWORD
sudo: required
services:
   - docker
script:
   - docker build -t zeidane/node2 .
   - docker images zeidane/node2

before_deploy:
   - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
deploy:
  provider: script 
  script: docker push zeidane/node2
  on:
    branch: master
